# Generated by Django 5.2.15 on 2026-07-05 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='shape_type',
            field=models.CharField(choices=[('polygon', 'Polygon'), ('rectangle', 'Rectangle'), ('point', 'Point'), ('polyline', 'Polyline')], default='polygon', max_length=12),
        ),
    ]
